STORIQONE_CHANGER_VTLCHANGER_SRC_DIR		:= src/changer/vtl_changer

STORIQONE_CHANGER_VTLCHANGER_BIN			:= bin/vtl_changer
STORIQONE_CHANGER_VTLCHANGER_CFLAG			:= -pthread
STORIQONE_CHANGER_VTLCHANGER_LD				:= -pthread -luuid -lstoriqone -lstoriqone-changer -Llib

STORIQONE_CHANGER_VTLCHANGER_DEPEND_LIB		:= lib/libstoriqone-changer.so

STORIQONE_CHANGER_VTLCHANGER_CHCKSUM_FILE	:= changer-vtlchanger.chcksum

STORIQONE_CHANGER_VTLCHANGER_LOCALE			:= storiqone-changer-vtl

BIN_SYMS									+= STORIQONE_CHANGER_VTLCHANGER
