STONE_JOB_FORMATMEDIA_SRC_DIR		:= src/job/format-media

STONE_JOB_FORMATMEDIA_BIN			:= bin/job_format-media
STONE_JOB_FORMATMEDIA_CFLAG			:= -pthread
STONE_JOB_FORMATMEDIA_LD			:= -pthread -lstone -lstone-job -luuid -Llib

STONE_JOB_FORMATMEDIA_DEPEND_LIB	:= lib/libstone-job.so

STONE_JOB_FORMATMEDIA_CHCKSUM_FILE	:= job_format-media.chcksum

BIN_SYMS							+= STONE_JOB_FORMATMEDIA
