TEST_SRC_DIR		:= src/test
TEST_BUILD_DIR		:= ${BUILD_DIR}/test
TEST_DEPEND_DIR		:= ${DEPEND_DIR}/test

TEST_SRC_FILES		:= $(sort $(shell test -d ${TEST_SRC_DIR} && find ${TEST_SRC_DIR} -name '*.c'))
TEST_HEAD_FILES		:= $(sort $(shell test -d ${TEST_SRC_DIR} && find ${TEST_SRC_DIR} -name '*.h'))
TEST_OBJ_FILES		:= $(sort $(patsubst src/%.c,${BUILD_DIR}/%.o,${TEST_SRC_FILES}))
TEST_DEP_FILES		:= $(sort $(shell test -d ${TEST_DEPEND_DIR} && find ${TEST_DEPEND_DIR} -name '*.d'))

TEST_BIN			:= bin/test
TEST_CFLAG			:=
TEST_LD				:= -lstone -ldl -lcunit -Llib

TEST_DEPEND_LIB		:= lib/libstone.so

BIN_SYMS			+= TEST
