STONED_SRC_DIR		:= src/stoned

STONED_BIN			:= bin/stoned
STONED_CFLAG		:= -fPIC -pthread
STONED_LD			:= -pthread -lstone -Llib -Wl,-rpath,lib

STONED_DEPEND_LIB	:= lib/libstone.so

STONED_CHCKSUM_FILE	:= stoned.chcksum

STONED_LOCALE		:= locale/stoned

BIN_SYMS			+= STONED
