STORIQONE_CHECKSUM_RIPEMD_SRC_DIR		:= src/checksum/ripemd

STORIQONE_CHECKSUM_RIPEMD_BIN			:= lib/libchecksum-ripemd.so
STORIQONE_CHECKSUM_RIPEMD_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STORIQONE_CHECKSUM_RIPEMD_LD			:= -pthread -shared -lstoriqone -Llib -lcrypto

STORIQONE_CHECKSUM_RIPEMD_DEPEND_LIB	:= lib/libstoriqone.so

STORIQONE_CHECKSUM_RIPEMD_CHCKSUM_FILE	:= libchecksum-ripemd.chcksum

BIN_SYMS								+= STORIQONE_CHECKSUM_RIPEMD
