LOGGER_SRC_DIR		:= src/logger

LOGGER_BIN			:= bin/logger
LOGGER_CFLAG		:=
LOGGER_LD			:= -lstone -Llib -Wl,-rpath,lib

LOGGER_DEPEND_LIB	:= lib/libstone.so

LOGGER_CHCKSUM_FILE	:= logger.chcksum

BIN_SYMS			+= LOGGER
