LOGGER_SRC_DIR		:= src/logger

LOGGER_BIN			:= bin/logger
LOGGER_CFLAG		:= -fPIC -pthread
LOGGER_LD			:= -pthread -lstone -lstone-logger -Llib -Wl,-rpath,lib

LOGGER_DEPEND_LIB	:= lib/libstone-logger.so

LOGGER_CHCKSUM_FILE	:= logger.chcksum

LOGGER_LOCALE		:= locale/stone-logger

BIN_SYMS			+= LOGGER
