LIBSTONEDRIVE_SRC_DIR		:= src/libstone-drive

LIBSTONEDRIVE_CFLAG			:= -fPIC -pthread
LIBSTONEDRIVE_LIB			:= lib/libstone-drive.so
LIBSTONEDRIVE_LD			:= -shared -pthread -ldl -Wl,--version-script,src/libstone-drive/libstone-drive.map
LIBSTONEDRIVE_SONAME		:= libstone-drive.so.1
LIBSTONEDRIVE_LIB_VERSION	:= 1.2

LIBSTONEDRIVE_DEPEND_LIB	:= src/libstone-drive/libstone-drive.map lib/libstone.so

LIBSTONEDRIVE_CHCKSUM_FILE	:= libstone-drive.chcksum

BIN_SYMS					+= LIBSTONEDRIVE
