STORIQONE_LOG_POSTGRESQL_SRC_DIR		:= src/log/postgresql

STORIQONE_LOG_POSTGRESQL_BIN			:= lib/liblog-postgresql.so
STORIQONE_LOG_POSTGRESQL_CFLAG			 = -pthread -fPIC -fvisibility=hidden ${LIB_PQ_CFLAGS}
STORIQONE_LOG_POSTGRESQL_LD				 = -pthread -shared -lstoriqone -Llib ${LIB_PQ_LD}

STORIQONE_LOG_POSTGRESQL_DEPEND_LIB		:= lib/libstoriqone.so

STORIQONE_LOG_POSTGRESQL_CHCKSUM_FILE	:= liblog-postgresql.chcksum

BIN_SYMS								+= STORIQONE_LOG_POSTGRESQL
