STONE_LOG_MARIADB_SRC_DIR		:= src/log/mariadb

STONE_LOG_MARIADB_BIN			:= lib/liblog-mariadb.so
STONE_LOG_MARIADB_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_LOG_MARIADB_LD			:= -pthread -shared -lstone -Llib -lmariadbclient

STONE_LOG_MARIADB_DEPEND_LIB	:= lib/libstone.so

STONE_LOG_MARIADB_CHCKSUM_FILE	:= liblog-mariadb.chcksum

BIN_SYMS						+= STONE_LOG_MARIADB
