-- Update Changer
ALTER TABLE Changer ADD COLUMN enable BOOLEAN NOT NULL DEFAULT TRUE;

-- Update Drive
ALTER TABLE Drive ADD COLUMN enable BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE Backup (
	id BIGSERIAL PRIMARY KEY,
	timestamp TIMESTAMP	NOT NULL DEFAULT now(),
	nbTape INTEGER NOT NULL DEFAULT 0,
	nbArchive INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE BackupVolume (
	id BIGSERIAL PRIMARY KEY,
    sequence INTEGER NOT NULL DEFAULT 0 CHECK (sequence >= 0),
    backup BIGINT NOT NULL REFERENCES Backup(id) ON DELETE CASCADE ON UPDATE CASCADE,
    tape INTEGER NOT NULL REFERENCES Tape(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    tapePosition INTEGER NOT NULL DEFAULT 0 CHECK (tapePosition >= 0)
);
