STONE_JOB_CHECKARCHIVE_SRC_DIR		:= src/module/job/check_archive

STONE_JOB_CHECKARCHIVE_BIN			:= lib/libjob-check-archive.so
STONE_JOB_CHECKARCHIVE_CFLAG		:= -pthread -fPIC -fvisibility=hidden
STONE_JOB_CHECKARCHIVE_LD			:= -pthread -shared

STONE_JOB_CHECKARCHIVE_DEPEND_LIB	:=

STONE_JOB_CHECKARCHIVE_CHCKSUM_FILE	:= libjob-check-archive.chcksum

BIN_SYMS							+= STONE_JOB_CHECKARCHIVE
