STONE_CHECKSUM_SHA256_SRC_DIR		:= src/module/checksum/sha256

STONE_CHECKSUM_SHA256_BIN			:= lib/libchecksum-sha256.so
STONE_CHECKSUM_SHA256_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_CHECKSUM_SHA256_LD			:= -pthread -shared -lcrypto

STONE_CHECKSUM_SHA256_DEPEND_LIB	:=

STONE_CHECKSUM_SHA256_CHCKSUM_FILE	:= libchecksum-sha256.chcksum

BIN_SYMS							+= STONE_CHECKSUM_SHA256
