STORIQONE_CHANGER_SCSICHANGER_SRC_DIR		:= src/changer/scsi_changer

STORIQONE_CHANGER_SCSICHANGER_BIN			:= bin/scsi_changer
STORIQONE_CHANGER_SCSICHANGER_CFLAG			:= -pthread
STORIQONE_CHANGER_SCSICHANGER_LD			:= -pthread -lstoriqone -lstoriqone-changer -Llib -Wl,-rpath,lib

STORIQONE_CHANGER_SCSICHANGER_DEPEND_LIB	:= lib/libstoriqone-changer.so

STORIQONE_CHANGER_SCSICHANGER_CHCKSUM_FILE	:= changer-scsichanger.chcksum

STORIQONE_CHANGER_SCSICHANGER_LOCALE		:= locale/storiqone-changer-scsi

BIN_SYMS									+= STORIQONE_CHANGER_SCSICHANGER
