STONE_CHECKSUM_CRC32_SRC_DIR		:= src/module/checksum/crc32

STONE_CHECKSUM_CRC32_BIN			:= lib/libchecksum-crc32.so
STONE_CHECKSUM_CRC32_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_CHECKSUM_CRC32_LD				:= -pthread -shared -lz

STONE_CHECKSUM_CRC32_DEPEND_LIB		:=

STONE_CHECKSUM_CRC32_CHCKSUM_FILE	:= libchecksum-crc32.chcksum

BIN_SYMS							+= STONE_CHECKSUM_CRC32
