STONE_JOB_SAVE_SRC_DIR		:= src/module/job/save

STONE_JOB_SAVE_BIN			:= lib/libjob-save.so
STONE_JOB_SAVE_CFLAG		:= -pthread -fPIC -fvisibility=hidden
STONE_JOB_SAVE_LD			:= -pthread -shared -lmagic

STONE_JOB_SAVE_DEPEND_LIB	:=

STONE_JOB_SAVE_CHCKSUM_FILE	:= libjob-dave.chcksum

BIN_SYMS					+= STONE_JOB_SAVE
