STORIQONE_JOB_ERASEMEDIA_SRC_DIR		:= src/job/erase-media

STORIQONE_JOB_ERASEMEDIA_BIN			:= bin/job_erase-media
STORIQONE_JOB_ERASEMEDIA_CFLAG			:= -pthread
STORIQONE_JOB_ERASEMEDIA_LD				:= -pthread -lstoriqone -lstoriqone-job -Llib

STORIQONE_JOB_ERASEMEDIA_DEPEND_LIB		:= lib/libstoriqone-job.so

STORIQONE_JOB_ERASEMEDIA_CHCKSUM_FILE	:= job_erase-media.chcksum

STORIQONE_JOB_ERASEMEDIA_LOCALE			:= locale/storiqone-job-erase-media

BIN_SYMS								+= STORIQONE_JOB_ERASEMEDIA
