#! /bin/sh
### BEGIN INIT INFO
# Provides:          stoned
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: StOne daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/stoned
NAME=stoned
DESC="stoned daemon"
PARAMETERS="-d"

test -f $DAEMON || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "

	storiqonectl start
	STATUS=$?

	echo "$NAME."
	exit $STATUS
	;;
  stop)
	echo -n "Stopping $DESC: "

	storiqonectl stop
	STATUS=$?

	echo "$NAME."
	exit $STATUS
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "

	storiqonectl stop
	STATUS=$?

	if [ "$STATUS" -ne 0 ]; then
		echo -n "failed"
		exit $STATUS
	fi

	sleep 1

	storiqonectl start
	STATUS=$?

	echo "$NAME."
	exit $STATUS
	;;
  restart-if-running)
	set +e
	echo -n "Restarting $DESC (if running): "
	if storiqonectl status; then
		sleep 1
		storiqonectl start
	fi
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
