CUNIT_SRC_DIR		:= test/cunit

CUNIT_BIN			:= bin/cunit
CUNIT_CFLAG			:=
CUNIT_LD			:= -lstone -ldl -lcunit -Llib

CUNIT_DEPEND_LIB	:= lib/libstone.so

CUNIT_CHCKSUM_FILE	:= cunit.chcksum

TEST_BIN_SYMS		+= CUNIT
