lib/libstoriqone*.so.* usr/lib
lib/libchecksum*.so usr/lib/storiqone/1.2/lib

usr/share/locale/es/LC_MESSAGES/libstoriqone.mo
usr/share/locale/es/LC_MESSAGES/libstoriqone-changer.mo
usr/share/locale/es/LC_MESSAGES/libstoriqone-drive.mo
usr/share/locale/es/LC_MESSAGES/libstoriqone-job.mo

usr/share/locale/fr/LC_MESSAGES/libstoriqone.mo
usr/share/locale/fr/LC_MESSAGES/libstoriqone-changer.mo
usr/share/locale/fr/LC_MESSAGES/libstoriqone-drive.mo
usr/share/locale/fr/LC_MESSAGES/libstoriqone-job.mo

debian/rules /usr/share/doc/libstoriqone-1.2
