debian/tmp/etc/storiq/storiqone.conf

bin/job_* usr/lib/storiqone/1.3/job
bin/logger usr/lib/storiqone/1.3/bin
bin/scsi_changer usr/lib/storiqone/1.3/bin
bin/standalone_changer usr/lib/storiqone/1.3/bin
bin/storiqonectl usr/sbin
bin/storiqoned usr/sbin
bin/tape_drive usr/lib/storiqone/1.3/bin
bin/vtl_changer usr/lib/storiqone/1.3/bin
bin/vtl_drive usr/lib/storiqone/1.3/bin

usr/share/locale/es/LC_MESSAGES/storiqone-changer-*.mo
usr/share/locale/es/LC_MESSAGES/storiqone-drive-*.mo
usr/share/locale/es/LC_MESSAGES/storiqone-job-*.mo
usr/share/locale/es/LC_MESSAGES/storiqone-logger.mo
usr/share/locale/es/LC_MESSAGES/storiqonectl.mo
usr/share/locale/es/LC_MESSAGES/storiqoned.mo

usr/share/locale/fr/LC_MESSAGES/storiqone-changer-*.mo
usr/share/locale/fr/LC_MESSAGES/storiqone-drive-*.mo
usr/share/locale/fr/LC_MESSAGES/storiqone-job-*.mo
usr/share/locale/fr/LC_MESSAGES/storiqone-logger.mo
usr/share/locale/fr/LC_MESSAGES/storiqonectl.mo
usr/share/locale/fr/LC_MESSAGES/storiqoned.mo
