STONE_CHECKSUM_WHIRLPOOL_SRC_DIR		:= src/module/checksum/whirlpool

STONE_CHECKSUM_WHIRLPOOL_BIN			:= lib/libchecksum-whirlpool.so
STONE_CHECKSUM_WHIRLPOOL_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_CHECKSUM_WHIRLPOOL_LD				:= -pthread -shared -lcrypto

STONE_CHECKSUM_WHIRLPOOL_DEPEND_LIB		:=

STONE_CHECKSUM_WHIRLPOOL_CHCKSUM_FILE	:= libchecksum-whirlpool.chcksum

BIN_SYMS								+= STONE_CHECKSUM_WHIRLPOOL
