#! /usr/bin/perl

use strict;
use warnings;

my ($param) = @ARGV;
$param = '' unless defined $param;

my $current_po_file;
my $current_po_line;
my $current_src_file;
my $current_src_line;
my $current_msg_id;

open(my $fd, qq#git grep -n -B3 ' ""' -- locale/$param |#);
while (<$fd>) {
	chomp;

	if (/:\s(.+):(\d+)$/) {
		$current_src_file = $1;
		$current_src_line = $2;
	}
	if (/msgid\s+"(.+)"$/) {
		$current_msg_id = $1;
	}
	elsif (/^(.+):(\d+):msgstr/) {
		$current_po_file = $1;
		$current_po_line = int $2;

		printf "In po file '%s' at line #%d\n", $current_po_file, $current_po_line;
		printf "In src file '%s' at line #%d: %s\n\n", $current_src_file, $current_src_line, $current_msg_id;
	}
}
close $fd;

