#! /usr/bin/perl

use strict;
use warnings;

my ($param) = @ARGV;
$param = '' unless defined $param;

my $current_file;
my $current_line;
my $current_msg_id;

open(my $fd, qq#git grep -B1 ' ""' -- locale/$param |#);
while (<$fd>) {
	chomp;

	if (/msgid\s+"(.+)"$/) {
		$current_msg_id = $1;
	}
	elsif (/^(.+):(\d+):msgstr/) {
		$current_file = $1;
		$current_line = int $2;

		printf "In file '%s' at line #%d: %s\n", $current_file, $current_line, $current_msg_id;
	}
}
close $fd;

