#! /bin/sh
### BEGIN INIT INFO
# Provides:          stoned
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: StOne daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/stoned
NAME=stoned
DESC="stoned daemon"

test -f $DAEMON || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --user daemon --chuid daemon --exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --user daemon --exec $DAEMON
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --user daemon --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --user daemon --chuid daemon --exec $DAEMON
	echo "$NAME."
	;;
  restart-if-running)
	set +e
	echo -n "Restarting $DESC (if running): "
	if start-stop-daemon --stop --quiet --user daemon --exec $DAEMON; then
		sleep 1
		start-stop-daemon --start --quiet --user daemon --chuid daemon --exec $DAEMON
	fi
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
