STONECTL_SRC_DIR		:= src/stonectl

STONECTL_BIN			:= bin/stonectl
STONECTL_CFLAG			:= -fPIC -pthread
STONECTL_LD				:= -pthread -lstone -Llib -Wl,-rpath,lib -luuid

STONECTL_DEPEND_LIB		:= lib/libstone.so

STONECTL_CHCKSUM_FILE	:= stonectl.chcksum

BIN_SYMS				+= STONECTL
