STONECTL_SRC_DIR		:= src/stonectl

STONECTL_BIN			:= bin/stonectl
STONECTL_CFLAG			:=
STONECTL_LD				:= -lstone -Llib -Wl,-rpath,lib

STONECTL_DEPEND_LIB		:= lib/libstone.so

STONECTL_CHCKSUM_FILE	:= stonectl.chcksum

BIN_SYMS				+= STONECTL
