STONE_JOB_COPYARCHIVE_SRC_DIR		:= src/module/job/copy_archive

STONE_JOB_COPYARCHIVE_BIN			:= lib/libjob-copy-archive.so
STONE_JOB_COPYARCHIVE_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_JOB_COPYARCHIVE_LD			:= -pthread -shared

STONE_JOB_COPYARCHIVE_DEPEND_LIB	:=

STONE_JOB_COPYARCHIVE_CHCKSUM_FILE	:= libjob-copy-archive.chcksum

BIN_SYMS							+= STONE_JOB_COPYARCHIVE
