STORIQONE_JOB_CREATE_ARCHIVE_SRC_DIR		:= src/job/create-archive

STORIQONE_JOB_CREATE_ARCHIVE_BIN			:= bin/job_create-archive
STORIQONE_JOB_CREATE_ARCHIVE_CFLAG			:= -pthread
STORIQONE_JOB_CREATE_ARCHIVE_LD				:= -pthread -lstoriqone -lstoriqone-job -luuid -Llib

STORIQONE_JOB_CREATE_ARCHIVE_DEPEND_LIB		:= lib/libstoriqone-job.so

STORIQONE_JOB_CREATE_ARCHIVE_CHCKSUM_FILE	:= job_create-archive.chcksum

STORIQONE_JOB_CREATE_ARCHIVE_LOCALE			:= locale/storiqone-job-create-archive

BIN_SYMS									+= STORIQONE_JOB_CREATE_ARCHIVE
