STONE_CHECKSUM_SHA224_SRC_DIR		:= src/module/checksum/sha224

STONE_CHECKSUM_SHA224_BIN			:= lib/libchecksum-sha224.so
STONE_CHECKSUM_SHA224_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_CHECKSUM_SHA224_LD			:= -pthread -shared -lcrypto

STONE_CHECKSUM_SHA224_DEPEND_LIB	:=

STONE_CHECKSUM_SHA224_CHCKSUM_FILE	:= libchecksum-sha224.chcksum

BIN_SYMS							+= STONE_CHECKSUM_SHA224
