STORIQONE_DRIVE_TAPEDRIVE_SRC_DIR		:= src/drive/tape_drive

STORIQONE_DRIVE_TAPEDRIVE_BIN			:= bin/tape_drive
STORIQONE_DRIVE_TAPEDRIVE_CFLAG			:= -pthread
STORIQONE_DRIVE_TAPEDRIVE_LD			:= -pthread -lstoriqone -lstoriqone-drive -Llib -Wl,-rpath,lib

STORIQONE_DRIVE_TAPEDRIVE_DEPEND_LIB	:= lib/libstoriqone-drive.so

STORIQONE_DRIVE_TAPEDRIVE_CHCKSUM_FILE	:= drive-tapedrive.chcksum

STORIQONE_DRIVE_TAPEDRIVE_LOCALE		:= locale/storiqone-drive-tape

BIN_SYMS								+= STORIQONE_DRIVE_TAPEDRIVE
