STONE_DRIVE_TAPEDRIVE_SRC_DIR		:= src/drive/tape_drive

STONE_DRIVE_TAPEDRIVE_BIN			:= bin/tape_drive
STONE_DRIVE_TAPEDRIVE_CFLAG			:= -pthread
STONE_DRIVE_TAPEDRIVE_LD			:= -pthread -lstone -lstone-drive -Llib

STONE_DRIVE_TAPEDRIVE_DEPEND_LIB	:= lib/libstone-drive.so

STONE_DRIVE_TAPEDRIVE_CHCKSUM_FILE	:= drive-tapedrive.chcksum

BIN_SYMS							+= STONE_DRIVE_TAPEDRIVE
