STONE_CHECKSUM_SHA512_SRC_DIR		:= src/module/checksum/sha512

STONE_CHECKSUM_SHA512_BIN			:= lib/libchecksum-sha512.so
STONE_CHECKSUM_SHA512_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_CHECKSUM_SHA512_LD			:= -pthread -shared -lcrypto

STONE_CHECKSUM_SHA512_DEPEND_LIB	:=

STONE_CHECKSUM_SHA512_CHCKSUM_FILE	:= libchecksum-sha512.chcksum

BIN_SYMS							+= STONE_CHECKSUM_SHA512
