LIBSTORIQONE_SRC_DIR		:= src/libstoriqone

LIBSTORIQONE_CFLAG			:= -fPIC -pthread
LIBSTORIQONE_LIB			:= lib/libstoriqone.so
LIBSTORIQONE_LD				:= -shared -pthread -ldl
LIBSTORIQONE_SONAME			:= libstoriqone.so.1
LIBSTORIQONE_LIB_VERSION	:= 1.2

LIBSTORIQONE_DEPEND_LIB		:=

LIBSTORIQONE_CHCKSUM_FILE	:= libstoriqone.chcksum

LIBSTORIQONE_LOCALE			:= locale/libstoriqone

BIN_SYMS					+= LIBSTORIQONE
