STONE_JOB_RESTOREARCHIVE_SRC_DIR		:= src/module/job/restore_archive

STONE_JOB_RESTOREARCHIVE_BIN			:= lib/libjob-restore-archive.so
STONE_JOB_RESTOREARCHIVE_CFLAG			:= -pthread -fPIC -fvisibility=hidden
STONE_JOB_RESTOREARCHIVE_LD				:= -pthread -shared -lmagic

STONE_JOB_RESTOREARCHIVE_DEPEND_LIB		:=

STONE_JOB_RESTOREARCHIVE_CHCKSUM_FILE	:= libjob-restore-archive.chcksum

BIN_SYMS								+= STONE_JOB_RESTOREARCHIVE
