STORIQONE_JOB_RESTOREARCHIVE_SRC_DIR		:= src/job/restore-archive

STORIQONE_JOB_RESTOREARCHIVE_BIN			:= bin/job_restore-archive
STORIQONE_JOB_RESTOREARCHIVE_CFLAG			:= -pthread
STORIQONE_JOB_RESTOREARCHIVE_LD				:= -pthread -lstoriqone -lstoriqone-job -Llib

STORIQONE_JOB_RESTOREARCHIVE_DEPEND_LIB		:= lib/libstoriqone-job.so

STORIQONE_JOB_RESTOREARCHIVE_CHCKSUM_FILE	:= job_restore-archive.chcksum

STORIQONE_JOB_RESTOREARCHIVE_LOCALE			:= locale/storiqone-job-restore-archive

BIN_SYMS									+= STORIQONE_JOB_RESTOREARCHIVE
