STORIQONE_JOB_COPYARCHIVE_SRC_DIR		:= src/job/copy-archive

STORIQONE_JOB_COPYARCHIVE_BIN			:= bin/job_copy-archive
STORIQONE_JOB_COPYARCHIVE_CFLAG			 = -pthread ${LIB_UUID_CFLAGS}
STORIQONE_JOB_COPYARCHIVE_LD			 = -pthread -lstoriqone -lstoriqone-job -Llib ${LIB_UUID_LD}

STORIQONE_JOB_COPYARCHIVE_DEPEND_LIB	:= lib/libstoriqone-job.so

STORIQONE_JOB_COPYARCHIVE_CHCKSUM_FILE	:= job_copy-archive.chcksum

STORIQONE_JOB_COPYARCHIVE_LOCALE		:= locale/storiqone-job-copy-archive

BIN_SYMS								+= STORIQONE_JOB_COPYARCHIVE
